name: Rust CI/CD

on:
  push:
    branches: [ "main" ]   
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Show Rust version
        run: |
          rustc --version
          cargo --version

      - name: Build
        run: cargo build --verbose

      - name: Run Integration Tests
        run: cargo test --test integration_udp --verbose

      - name: Run Stress Tests
        run: cargo test --test stress_test --verbose

      - name: Build Release Package
        run: cargo build --release

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-binaries
          path: target/release/*

