[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = "4.5.45"
parking_lot = "0.12.4"
protocol = { version = "0.1.0", path = "../protocol" }
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
